version: "3.9"

services:
  valkey:
    image: valkey/valkey:8.1.3-alpine
    container_name: valkey
    ports:
      - "6379:6379"
    volumes:
      - valkey-data:/data
  worker-manager:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: worker-manager
    environment:
      - HTTP_PORT=3000
      - GRPC_PORT=3001
      - VALKEY_ADDR=valkey:6379
    ports:
      - "3000:3000"
      - "3001:3001"
    depends_on:
      - valkey

volumes:
  valkey-data:

