// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: worker/worker.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateWorkerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SaveDuration  int64                  `protobuf:"varint,1,opt,name=save_duration,json=saveDuration,proto3" json:"save_duration,omitempty"` // in seconds
	WorkerMsg     string                 `protobuf:"bytes,2,opt,name=worker_msg,json=workerMsg,proto3" json:"worker_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWorkerRequest) Reset() {
	*x = CreateWorkerRequest{}
	mi := &file_worker_worker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWorkerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWorkerRequest) ProtoMessage() {}

func (x *CreateWorkerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_worker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWorkerRequest.ProtoReflect.Descriptor instead.
func (*CreateWorkerRequest) Descriptor() ([]byte, []int) {
	return file_worker_worker_proto_rawDescGZIP(), []int{0}
}

func (x *CreateWorkerRequest) GetSaveDuration() int64 {
	if x != nil {
		return x.SaveDuration
	}
	return 0
}

func (x *CreateWorkerRequest) GetWorkerMsg() string {
	if x != nil {
		return x.WorkerMsg
	}
	return ""
}

type CreateWorkerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      int64                  `protobuf:"varint,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWorkerResponse) Reset() {
	*x = CreateWorkerResponse{}
	mi := &file_worker_worker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWorkerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWorkerResponse) ProtoMessage() {}

func (x *CreateWorkerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worker_worker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWorkerResponse.ProtoReflect.Descriptor instead.
func (*CreateWorkerResponse) Descriptor() ([]byte, []int) {
	return file_worker_worker_proto_rawDescGZIP(), []int{1}
}

func (x *CreateWorkerResponse) GetWorkerId() int64 {
	if x != nil {
		return x.WorkerId
	}
	return 0
}

func (x *CreateWorkerResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type CountWorkersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountWorkersRequest) Reset() {
	*x = CountWorkersRequest{}
	mi := &file_worker_worker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountWorkersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountWorkersRequest) ProtoMessage() {}

func (x *CountWorkersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_worker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountWorkersRequest.ProtoReflect.Descriptor instead.
func (*CountWorkersRequest) Descriptor() ([]byte, []int) {
	return file_worker_worker_proto_rawDescGZIP(), []int{2}
}

type CountWorkersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerCount   int64                  `protobuf:"varint,1,opt,name=worker_count,json=workerCount,proto3" json:"worker_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountWorkersResponse) Reset() {
	*x = CountWorkersResponse{}
	mi := &file_worker_worker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountWorkersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountWorkersResponse) ProtoMessage() {}

func (x *CountWorkersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worker_worker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountWorkersResponse.ProtoReflect.Descriptor instead.
func (*CountWorkersResponse) Descriptor() ([]byte, []int) {
	return file_worker_worker_proto_rawDescGZIP(), []int{3}
}

func (x *CountWorkersResponse) GetWorkerCount() int64 {
	if x != nil {
		return x.WorkerCount
	}
	return 0
}

type GetWorkerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      int64                  `protobuf:"varint,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkerRequest) Reset() {
	*x = GetWorkerRequest{}
	mi := &file_worker_worker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkerRequest) ProtoMessage() {}

func (x *GetWorkerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_worker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkerRequest.ProtoReflect.Descriptor instead.
func (*GetWorkerRequest) Descriptor() ([]byte, []int) {
	return file_worker_worker_proto_rawDescGZIP(), []int{4}
}

func (x *GetWorkerRequest) GetWorkerId() int64 {
	if x != nil {
		return x.WorkerId
	}
	return 0
}

type GetWorkerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      int64                  `protobuf:"varint,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	WorkerMsg     string                 `protobuf:"bytes,2,opt,name=worker_msg,json=workerMsg,proto3" json:"worker_msg,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkerResponse) Reset() {
	*x = GetWorkerResponse{}
	mi := &file_worker_worker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkerResponse) ProtoMessage() {}

func (x *GetWorkerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worker_worker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkerResponse.ProtoReflect.Descriptor instead.
func (*GetWorkerResponse) Descriptor() ([]byte, []int) {
	return file_worker_worker_proto_rawDescGZIP(), []int{5}
}

func (x *GetWorkerResponse) GetWorkerId() int64 {
	if x != nil {
		return x.WorkerId
	}
	return 0
}

func (x *GetWorkerResponse) GetWorkerMsg() string {
	if x != nil {
		return x.WorkerMsg
	}
	return ""
}

func (x *GetWorkerResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetWorkerDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      int64                  `protobuf:"varint,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkerDataRequest) Reset() {
	*x = GetWorkerDataRequest{}
	mi := &file_worker_worker_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkerDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkerDataRequest) ProtoMessage() {}

func (x *GetWorkerDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_worker_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkerDataRequest.ProtoReflect.Descriptor instead.
func (*GetWorkerDataRequest) Descriptor() ([]byte, []int) {
	return file_worker_worker_proto_rawDescGZIP(), []int{6}
}

func (x *GetWorkerDataRequest) GetWorkerId() int64 {
	if x != nil {
		return x.WorkerId
	}
	return 0
}

type GetWorkerDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LastModified  string                 `protobuf:"bytes,1,opt,name=last_modified,json=lastModified,proto3" json:"last_modified,omitempty"`
	CachedMsg     string                 `protobuf:"bytes,2,opt,name=cached_msg,json=cachedMsg,proto3" json:"cached_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkerDataResponse) Reset() {
	*x = GetWorkerDataResponse{}
	mi := &file_worker_worker_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkerDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkerDataResponse) ProtoMessage() {}

func (x *GetWorkerDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worker_worker_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkerDataResponse.ProtoReflect.Descriptor instead.
func (*GetWorkerDataResponse) Descriptor() ([]byte, []int) {
	return file_worker_worker_proto_rawDescGZIP(), []int{7}
}

func (x *GetWorkerDataResponse) GetLastModified() string {
	if x != nil {
		return x.LastModified
	}
	return ""
}

func (x *GetWorkerDataResponse) GetCachedMsg() string {
	if x != nil {
		return x.CachedMsg
	}
	return ""
}

type UpdateWorkerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      int64                  `protobuf:"varint,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	WorkerMsg     string                 `protobuf:"bytes,2,opt,name=worker_msg,json=workerMsg,proto3" json:"worker_msg,omitempty"`
	SaveDuration  int64                  `protobuf:"varint,3,opt,name=save_duration,json=saveDuration,proto3" json:"save_duration,omitempty"` // in seconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWorkerRequest) Reset() {
	*x = UpdateWorkerRequest{}
	mi := &file_worker_worker_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWorkerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWorkerRequest) ProtoMessage() {}

func (x *UpdateWorkerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_worker_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWorkerRequest.ProtoReflect.Descriptor instead.
func (*UpdateWorkerRequest) Descriptor() ([]byte, []int) {
	return file_worker_worker_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateWorkerRequest) GetWorkerId() int64 {
	if x != nil {
		return x.WorkerId
	}
	return 0
}

func (x *UpdateWorkerRequest) GetWorkerMsg() string {
	if x != nil {
		return x.WorkerMsg
	}
	return ""
}

func (x *UpdateWorkerRequest) GetSaveDuration() int64 {
	if x != nil {
		return x.SaveDuration
	}
	return 0
}

type UpdateWorkerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWorkerResponse) Reset() {
	*x = UpdateWorkerResponse{}
	mi := &file_worker_worker_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWorkerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWorkerResponse) ProtoMessage() {}

func (x *UpdateWorkerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worker_worker_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWorkerResponse.ProtoReflect.Descriptor instead.
func (*UpdateWorkerResponse) Descriptor() ([]byte, []int) {
	return file_worker_worker_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateWorkerResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type DeleteWorkerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      int64                  `protobuf:"varint,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWorkerRequest) Reset() {
	*x = DeleteWorkerRequest{}
	mi := &file_worker_worker_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWorkerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWorkerRequest) ProtoMessage() {}

func (x *DeleteWorkerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_worker_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWorkerRequest.ProtoReflect.Descriptor instead.
func (*DeleteWorkerRequest) Descriptor() ([]byte, []int) {
	return file_worker_worker_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteWorkerRequest) GetWorkerId() int64 {
	if x != nil {
		return x.WorkerId
	}
	return 0
}

type DeleteWorkerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWorkerResponse) Reset() {
	*x = DeleteWorkerResponse{}
	mi := &file_worker_worker_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWorkerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWorkerResponse) ProtoMessage() {}

func (x *DeleteWorkerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worker_worker_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWorkerResponse.ProtoReflect.Descriptor instead.
func (*DeleteWorkerResponse) Descriptor() ([]byte, []int) {
	return file_worker_worker_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteWorkerResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_worker_worker_proto protoreflect.FileDescriptor

const file_worker_worker_proto_rawDesc = "" +
	"\n" +
	"\x13worker/worker.proto\"Y\n" +
	"\x13CreateWorkerRequest\x12#\n" +
	"\rsave_duration\x18\x01 \x01(\x03R\fsaveDuration\x12\x1d\n" +
	"\n" +
	"worker_msg\x18\x02 \x01(\tR\tworkerMsg\"E\n" +
	"\x14CreateWorkerResponse\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\x03R\bworkerId\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"\x15\n" +
	"\x13CountWorkersRequest\"9\n" +
	"\x14CountWorkersResponse\x12!\n" +
	"\fworker_count\x18\x01 \x01(\x03R\vworkerCount\"/\n" +
	"\x10GetWorkerRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\x03R\bworkerId\"g\n" +
	"\x11GetWorkerResponse\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\x03R\bworkerId\x12\x1d\n" +
	"\n" +
	"worker_msg\x18\x02 \x01(\tR\tworkerMsg\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"3\n" +
	"\x14GetWorkerDataRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\x03R\bworkerId\"[\n" +
	"\x15GetWorkerDataResponse\x12#\n" +
	"\rlast_modified\x18\x01 \x01(\tR\flastModified\x12\x1d\n" +
	"\n" +
	"cached_msg\x18\x02 \x01(\tR\tcachedMsg\"v\n" +
	"\x13UpdateWorkerRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\x03R\bworkerId\x12\x1d\n" +
	"\n" +
	"worker_msg\x18\x02 \x01(\tR\tworkerMsg\x12#\n" +
	"\rsave_duration\x18\x03 \x01(\x03R\fsaveDuration\"(\n" +
	"\x14UpdateWorkerResponse\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\"2\n" +
	"\x13DeleteWorkerRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\x03R\bworkerId\"(\n" +
	"\x14DeleteWorkerResponse\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg2\xf7\x02\n" +
	"\rWorkerService\x12;\n" +
	"\fCreateWorker\x12\x14.CreateWorkerRequest\x1a\x15.CreateWorkerResponse\x12;\n" +
	"\fCountWorkers\x12\x14.CountWorkersRequest\x1a\x15.CountWorkersResponse\x122\n" +
	"\tGetWorker\x12\x11.GetWorkerRequest\x1a\x12.GetWorkerResponse\x12>\n" +
	"\rGetWorkerData\x12\x15.GetWorkerDataRequest\x1a\x16.GetWorkerDataResponse\x12;\n" +
	"\fUpdateWorker\x12\x14.UpdateWorkerRequest\x1a\x15.UpdateWorkerResponse\x12;\n" +
	"\fDeleteWorker\x12\x14.DeleteWorkerRequest\x1a\x15.DeleteWorkerResponseB+Z)goroutine-manager/internal/web/grpc.pb;pbb\x06proto3"

var (
	file_worker_worker_proto_rawDescOnce sync.Once
	file_worker_worker_proto_rawDescData []byte
)

func file_worker_worker_proto_rawDescGZIP() []byte {
	file_worker_worker_proto_rawDescOnce.Do(func() {
		file_worker_worker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_worker_worker_proto_rawDesc), len(file_worker_worker_proto_rawDesc)))
	})
	return file_worker_worker_proto_rawDescData
}

var file_worker_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_worker_worker_proto_goTypes = []any{
	(*CreateWorkerRequest)(nil),   // 0: CreateWorkerRequest
	(*CreateWorkerResponse)(nil),  // 1: CreateWorkerResponse
	(*CountWorkersRequest)(nil),   // 2: CountWorkersRequest
	(*CountWorkersResponse)(nil),  // 3: CountWorkersResponse
	(*GetWorkerRequest)(nil),      // 4: GetWorkerRequest
	(*GetWorkerResponse)(nil),     // 5: GetWorkerResponse
	(*GetWorkerDataRequest)(nil),  // 6: GetWorkerDataRequest
	(*GetWorkerDataResponse)(nil), // 7: GetWorkerDataResponse
	(*UpdateWorkerRequest)(nil),   // 8: UpdateWorkerRequest
	(*UpdateWorkerResponse)(nil),  // 9: UpdateWorkerResponse
	(*DeleteWorkerRequest)(nil),   // 10: DeleteWorkerRequest
	(*DeleteWorkerResponse)(nil),  // 11: DeleteWorkerResponse
}
var file_worker_worker_proto_depIdxs = []int32{
	0,  // 0: WorkerService.CreateWorker:input_type -> CreateWorkerRequest
	2,  // 1: WorkerService.CountWorkers:input_type -> CountWorkersRequest
	4,  // 2: WorkerService.GetWorker:input_type -> GetWorkerRequest
	6,  // 3: WorkerService.GetWorkerData:input_type -> GetWorkerDataRequest
	8,  // 4: WorkerService.UpdateWorker:input_type -> UpdateWorkerRequest
	10, // 5: WorkerService.DeleteWorker:input_type -> DeleteWorkerRequest
	1,  // 6: WorkerService.CreateWorker:output_type -> CreateWorkerResponse
	3,  // 7: WorkerService.CountWorkers:output_type -> CountWorkersResponse
	5,  // 8: WorkerService.GetWorker:output_type -> GetWorkerResponse
	7,  // 9: WorkerService.GetWorkerData:output_type -> GetWorkerDataResponse
	9,  // 10: WorkerService.UpdateWorker:output_type -> UpdateWorkerResponse
	11, // 11: WorkerService.DeleteWorker:output_type -> DeleteWorkerResponse
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_worker_worker_proto_init() }
func file_worker_worker_proto_init() {
	if File_worker_worker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_worker_worker_proto_rawDesc), len(file_worker_worker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_worker_worker_proto_goTypes,
		DependencyIndexes: file_worker_worker_proto_depIdxs,
		MessageInfos:      file_worker_worker_proto_msgTypes,
	}.Build()
	File_worker_worker_proto = out.File
	file_worker_worker_proto_goTypes = nil
	file_worker_worker_proto_depIdxs = nil
}
